In [21]:
import pickle
import pandas as pd

In [57]:
new = pickle.load(open("save_and_results/new/journal/journal_new_remove_W/Moehne_lot_linear_results_stack.p", "rb"))
old = pickle.load(open("save_and_results/old/journal/journal_new_remove_W/Moehne_lot_linear_results_stack.p", "rb"))

In [65]:
new = pd.read_csv("save_and_results/new/igarss/fc_igarss_baseline/Lister_asc0_sarimax_selected_models.csv")
old = pd.read_csv("save_and_results/old/igarss/fc_igarss_baseline/Lister_asc0_sarimax_selected_models.csv")

In [66]:
new

,Unnamed: 0,Index,MSE,MAE,MSE_1step,MAE_1step,AIC,MAPE,MAPE_1step,P,...,STAU,T,M_Stau,M_T,Decompose,Interaction,Estimator,n_estimator,max_depth,learning_rate
0,0,720574,5.007018,1.740068,5.007018,1.740068,0.649399,0.649399,-191.528547,0,...,[0],[0],0,0,0,0,NaN,NaN,NaN,NaN
1,0,720593,26.457157,4.204382,26.457157,4.204382,1.853449,1.853449,-158.107699,0,...,[0],[],0,0,0,0,NaN,NaN,NaN,NaN
2,0,720808,3.518653,1.460344,3.518653,1.460344,0.733271,0.733271,-158.107699,0,...,[0],[],0,0,0,0,NaN,NaN,NaN,NaN
3,0,720906,12.484477,2.918899,12.484477,2.918899,1.536871,1.536871,-129.703510,0,...,[],[0],0,0,0,0,NaN,NaN,NaN,NaN

In [67]:
old

,Unnamed: 0,Index,MSE,MAE,MSE_1step,MAE_1step,AIC,MAPE,MAPE_1step,P,...,STAU,T,M_Stau,M_T,Decompose,Interaction,Estimator,n_estimator,max_depth,learning_rate
0,0,720574,5.007018,1.740068,5.007018,1.740068,0.649399,0.649399,-191.528547,0,...,[0],[0],0,0,0,0,NaN,NaN,NaN,NaN
1,0,720593,16.291822,3.186468,16.291822,3.186468,2.383974,2.383974,-191.528547,0,...,[0],[0],0,0,0,0,NaN,NaN,NaN,NaN
2,0,720808,17.063889,3.701141,17.063889,3.701141,1.363623,1.363623,-191.528547,0,...,[0],[0],0,0,0,0,NaN,NaN,NaN,NaN
3,0,720906,5.945601,1.864283,5.945601,1.864283,3.715544,3.715544,-191.528547,0,...,[0],[0],0,0,0,0,NaN,NaN,NaN,NaN